### ISSUE TITLE
Ticket created by mistake, sorry.

### ISSUE THREAD

**Issue by swyambhu9** [k5md/Steam-Bulk-Sell-webextension#10]

**Comment by swyambhu9** [comment]
I'm using Firefox 88.0

**Comment by swyambhu9** [comment]
Nvm it seemed to appear like that for sometime, I restarted the browser and the issue seems to have gone away.

**Comment by swyambhu9** [comment]
The issue was on my side, sorry for creating a ticket on it.

**Comment by k5md** [comment]
No problems
