### ISSUE TITLE
Не работает на карточках Steam + Пару предложений

### ISSUE THREAD

**Issue by fLAki1x** [k5md/Steam-Bulk-Sell-webextension#5]
Добрый день, возникла проблема при использовании расширения в Firefox, при продаже коллекционных карточек Steam расширение не реагирует на них, при выборе в логе не появляется информация о выбранной карточке, а при нажатии на продать выходить ошибка.
![error1](https://user-images.githubusercontent.com/73881770/97985947-2b974080-1e03-11eb-94a6-9178536356d0.jpg)
![error2](https://user-images.githubusercontent.com/73881770/97985956-2fc35e00-1e03-11eb-94f4-2bf7a6c08604.jpg)
И пару предложений, если же вам понравится не могли бы вы сделать так как показано на скрине. Чтобы при нажатии кнопки можно было сразу выделять предметы нажатием на картинку, а не на чекбокс. 
И еще 1 функцию при продаже предметов, чтобы можно было снизить цену на заданное значение, как это реализовано в Steam inventory Helper. Заранее спасибо!
![1](https://user-images.githubusercontent.com/73881770/97985930-2639f600-1e03-11eb-8597-0faeea14acfd.jpg)
![Регулировка цены](https://user-images.githubusercontent.com/73881770/97985961-30f48b00-1e03-11eb-9387-760d7e72721d.jpg)

**Comment by k5md** [comment]
Добрый вечер, @fLAki1x !
Насчёт предложений - спасибо, они правда сделают интерфейс более удобным, в течение завтрашнего дня добавлю!
Насчёт бага с выбором карточек, может потребоваться больше времени, так как воспроизвести его пока не удаётся ни на десктопе, ни на мобильном с разными скоростями соединения:
![somecardsdontwork](https://user-images.githubusercontent.com/6698666/98019208-84baa080-1e12-11eb-8db3-735b4230e246.png)
Если вы используете какие-либо расширения, которые блокируют или внедряют свой JS-код в страницы, например NoScript, напишите, это поможет определить, где проблема.

**Comment by fLAki1x** [comment]
Отключил все дополнения кроме вашего, все равно также не хочет показывать стоимость предметов в разделе Steam (карточки, смайли и тд.). На других играх все работает нормально.

**Comment by k5md** [comment]
> Отключил все дополнения кроме вашего, все равно также не хочет показывать стоимость предметов в разделе Steam (карточки, смайли и тд.). На других играх все работает нормально.
Огромное спасибо, информация помогла! Воспроизвёл, баг проявляется только тогда, когда есть несколько подкатегорий именно стимовских предметов (эта менюшка с опциями "Все предметы Steam", "Подарки" и так далее), завтра выпущу новую версию.

**Comment by fLAki1x** [comment]
Вам спасибо! Буду ждать обновления.

**Comment by k5md** [comment]
Вчера залил новую версию, если у вас ещё не обновилось или снята галка автообновления расширений, обновите вручную на странице расширений (about:addons).

![checkUpdates](https://user-images.githubusercontent.com/6698666/98243953-b8ff9f80-1f7f-11eb-9237-431babb81335.png)

**Comment by fLAki1x** [comment]
Да все заработало, большое спасибо за быстрый фикс. Удачи вам!
